---
- name: Verify IBMCLOUD_API_KEY injection
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Show via lookup
      debug:
        msg: "IBMCLOUD_API_KEY = {{ lookup('env', 'IBMCLOUD_API_KEY') }}"

    - name: Show via shell
      shell: echo $IBMCLOUD_API_KEY
      register: key_env

    - debug:
        var: key_env.stdout
